services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lls
    image: lls:v1
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - lls-network
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - data:/var/lib/redis
    networks:
      - lls-network
    env_file:
      - .env

networks:
  lls-network:
    driver: bridge

volumes:
  data: