spring:
  application:
    name: lls
  profiles:
    active: dev # @spring.profiles.active@
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: optional:file:.env[.properties]
  #  sql:
  #    init:
  #      schema-locations: database.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: true
  devtools:
    livereload:
      enabled: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
    web:
      pageable:
        one-indexed-parameters: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: info
    org:
      springframework.security: debug
      hibernate:
        stat: debug
        type.descriptor.sql: trace

server:
  error:
    include-message: always
  port: 8080

api:
  v1: api/v1

jwt:
  secret: ${JWT_SECRET}
  rsa-private-key: classpath:certs/privateKey.pem
  rsa-public-key: classpath:certs/publicKey.pem
  access-token: 8640000
  refresh-token: 8640000

country:
  api-key: ${COUNTRY_API_KEY}

rapid:
  api-key: ${RAPID_API_KEY}

geo:
  api-key: ${GEO_API_KEY}
  url: ${GEO_URL}

imgur:
  client-id: ${IMGUR_CLIENT_ID}
  client-secret: ${IMGUR_CLIENT_SECRET}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  url: ${CLOUDINARY_URL}

avatar:
  folder: ${AVATAR_FOLDER}
