springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

open:
  api:
    title: Document for Language Learning System API
    version: v1.0.0
    description: RESTful API for Language Learning System
    server:
      url: http://localhost:8080
      description: Local server