spring:
  application:
    name: lls
  profiles:
    active: dev # @spring.profiles.active@
  # cloud:
  #   gcp:
  #     sql:
  #       instance-connection-name: high-triode-423401-q3:asia-southeast1:lls
  #       database-name: lls
  #       credentials:
  #         location: ${GOOGLE_APPLICATION_CREDENTIALS}
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: optional:file:.env[.properties]
  #  sql:
  #    init:
  #      schema-locations: database.sql
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  devtools:
    livereload:
      enabled: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
    web:
      pageable:
        one-indexed-parameters: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    com:
      google:
        cloud:
          sql: debug
      zaxxer: 
        hikari: debug
    root: info
    org:
      springframework:
        security: debug
      hibernate:
        stat: debug
        type:
          descriptor:
            sql: trace

server:
  error:
    include-message: always
  port: 8080
  address: 0.0.0.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    info:
      enabled: true

api:
  v1: api/v1

jwt:
  secret: ${JWT_SECRET}
  rsa-private-key: classpath:certs/privateKey.pem
  rsa-public-key: classpath:certs/publicKey.pem
  access-token: 8640000
  refresh-token: 8640000

country:
  api-key: ${COUNTRY_API_KEY}

rapid:
  api-key: ${RAPID_API_KEY}

geo:
  api-key: ${GEO_API_KEY}
  url: ${GEO_URL}

imgur:
  client-id: ${IMGUR_CLIENT_ID}
  client-secret: ${IMGUR_CLIENT_SECRET}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  url: ${CLOUDINARY_URL}

avatar:
  folder: ${AVATAR_FOLDER}

material:
  folder: ${MATERIAL_FOLDER}

thumbnail:
  folder: ${THUMBNAILS_FOLDER}

vnPay:
  vnp_TmnCode: ${VNPAY_TMN_CODE}
  vnp_HashSecret: ${VNPAY_HASH_SECRET}
  vnp_Version: ${VNPAY_VERSION}
  vnp_ReturnUrl: ${VNPAY_RETURN_URL}
  vnp_Command: ${VNPAY_COMMAND}
  vnp_OrderType: ${VNPAY_ORDER_TYPE}
  vnp_CurrCode: ${VNPAY_CURR_CODE}
  vnp_Url: ${VNPAY_URL}
  vnp_Locale: ${VNPAY_LOCALE}

video:
  sdk:
    api-key: ${VIDEO_SDK_API_KEY}
    api-secret: ${VIDEO_SDK_API_SECRET}
    base-url: ${VIDEO_SDK_BASE_URL}

react:
  base-url: ${REACT_BASE_URL}
